# webspa on csproj example

ARG NODE_IMAGE=stefanscherer/node-windows:latest
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-nanoserver-1809 AS base
WORKDIR /app
EXPOSE 80

# Install Node to this container
FROM ${NODE_IMAGE} as node-build
WORKDIR /web
COPY Microservices/Bmt.Microservices.Client .
# Go to /web/ClientApp/ since package.json is there
WORKDIR /web/ClientApp
RUN npm install
RUN npm run build:prod

FROM mcr.microsoft.com/dotnet/core/sdk:2.2-nanoserver-1809 AS build
WORKDIR /src

COPY ["Microservices/Bmt.Microservices.Client/Bmt.Microservices.Client.csproj", "Microservices/Bmt.Microservices.Client/"]

RUN dotnet restore "Microservices/Bmt.Microservices.Client/Bmt.Microservices.Client.csproj" -p:RestoreUseSkipNonexistentTargets=false -nowarn:msb3202,nu1503

COPY . .
COPY --from=node-build /web/wwwroot /src/Microservices/Bmt.Microservices.Client/wwwroot
WORKDIR "/src/Microservices/Bmt.Microservices.Client"
RUN dotnet publish -c Release -o /app

FROM build AS publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Bmt.Microservices.Client.dll"]
